version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aiverse
      POSTGRES_USER: aiverse_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://aiverse_user:${POSTGRES_PASSWORD}@postgres:5432/aiverse
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      VITE_API_URL: ${API_URL}
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:
