services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aiverse
      POSTGRES_USER: aiverse_user
      POSTGRES_PASSWORD: aiverse_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # Изменяем порт на хосте на 5433, чтобы избежать конфликта с локальным PostgreSQL
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aiverse_user -d aiverse"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://aiverse_user:aiverse_password@postgres:5432/aiverse
      SECRET_KEY: your-secret-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      VITE_API_URL: http://localhost
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

  nginx:
    build: ./nginx
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./backend/uploads:/usr/share/nginx/html/uploads:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
