services:
  # Backend API
  - type: web
    name: aiverse-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
    repo: https://github.com/dorofi/aiverse

  # Frontend
  - type: web
    name: aiverse-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile.prod
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://aiverse-backend.onrender.com
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    autoDeploy: true
    branch: main
    repo: https://github.com/dorofi/aiverse
