services:
  - type: web
    name: aiverse-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    autoDeploy: true
    branch: main
    repo: https://github.com/dorofi/aiverse
