services:
  - type: web
    name: aiverse-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://aiverse-backend.onrender.com
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    autoDeploy: true
    branch: main
    repo: https://github.com/dorofi/aiverse
